// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRtE1wzzZrtu3IVc0VlPf5ckS-2QiX4Ho',
    appId: '1:627447759299:android:98a6015eff2035a9fcbd76',
    messagingSenderId: '627447759299',
    projectId: 'quizzymind-2cdf8',
    databaseURL: 'https://quizzymind-2cdf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzymind-2cdf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARnqjYq158wHkQq77BiIPWqcqkXidTU8I',
    appId: '1:627447759299:ios:bf4db10db2b8e2cefcbd76',
    messagingSenderId: '627447759299',
    projectId: 'quizzymind-2cdf8',
    databaseURL: 'https://quizzymind-2cdf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzymind-2cdf8.appspot.com',
    iosBundleId: 'com.example.quizzymind',
  );
}
